export const categoryList = [
  {
    id: 1,
    value: "Red",
    label: "Red",
  },
  {
    id: 2,
    value: "White",
    label: "White",
  },
  {
    id: 3,
    value: "Sparkling",
    label: "Sparkling",
  },
  {
    id: 4,
    value: "Ros",
    label: "Rose",
  },
  {
    id: 5,
    value: "Dessert",
    label: "Dessert",
  },
  {
    id: 6,
    value: "Fortified",
    label: "Fortified",
  },
];

export const ratingList = [
  {
    id: 1,
    value: "3",
    label: "★★★ 2.5 ~ 3.5",
  },
  {
    id: 2,
    value: "4",
    label: "★★★★ 3.5 ~ 4.5",
  },
  {
    id: 3,
    value: "5",
    // label: "5🌟",
    label: "★★★★★ 4.5 이상",
  },
];

export const dataList = [
  {
    id: 1,
    title: "lounge resort",
    serviceTime: "45-60min",
    deliveryFee: 3.44,
    category: "place",
    cuisine: "american",
    rating: 5,
    price: 2500,
    coverSrc: "/imagez/places/ameri.jpg",
  },
  {
    id: 2,
    title: "door urban",
    serviceTime: "15-20min",
    deliveryFee: 4.94,
    category: "place",
    cuisine: "italian",
    rating: 4,
    price: 1000,
    coverSrc: "/imagez/places/italian.jpg",
  },
  {
    id: 3,
    title: "chow",
    serviceTime: "30-22min",
    deliveryFee: 4.94,
    category: "place",
    cuisine: "chinese",
    rating: 3,
    price: 2000,
    coverSrc: "/imagez/places/china.jpg",
  },
  {
    id: 4,
    title: "wharf seafood",
    serviceTime: "10-18min",
    deliveryFee: 2.14,
    category: "place",
    cuisine: "american",
    rating: 1,
    price: 1800,
    coverSrc: "/imagez/places/sea.jpg",
  },
  {
    id: 5,
    title: "Tossin",
    serviceTime: "25-30min",
    deliveryFee: 6.79,
    category: "place",
    cuisine: "italian",
    rating: 5,
    price: 2000,
    coverSrc: "/imagez/places/italiian.jpg",
  },
  {
    id: 6,
    title: "stories noodles",
    serviceTime: "5-15min",
    deliveryFee: 2.87,
    category: "place",
    cuisine: "chinese",
    rating: 5,
    price: 3500,
    coverSrc: "/imagez/places/fookyew2.jpg",
  },
  {
    id: 7,
    title: "Nacho cheeseburger",
    serviceTime: "50-65min",
    deliveryFee: 8.5,
    category: "dish",
    cuisine: "american",
    rating: 2,
    price: 2200,
    coverSrc: "/imagez/dishes/nacho-burger.jpg",
  },
  {
    id: 8,
    title: "Mushroom Risotto",
    serviceTime: "10-15min",
    deliveryFee: 1.8,
    category: "dish",
    cuisine: "italian",
    rating: 1,
    price: 1900,
    coverSrc: "/imagez/dishes/Mushroom-Risotto-Recipe-1-1200.jpg",
  },
  {
    id: 9,
    title: "Shitake Fried Rice",
    serviceTime: "12-18min",
    deliveryFee: 3.33,
    category: "dish",
    cuisine: "chinese",
    rating: 4,
    price: 2750,
    coverSrc: "/imagez/dishes/shiitake-salmon-fried-rice-0218-103230720.jpg",
  },
  {
    id: 10,
    title: "Pesto chicken stew",
    serviceTime: "30-38min",
    deliveryFee: 1.9,
    category: "dish",
    cuisine: "american",
    rating: 2,
    price: 4350,
    coverSrc: "/imagez/dishes/pesto-chicken.jpg",
  },
  {
    id: 11,
    title: "Bruschetta",
    serviceTime: "16-20min",
    deliveryFee: 4.1,
    category: "dish",
    cuisine: "italian",
    rating: 3,
    price: 3300,
    coverSrc: "/imagez/dishes/as-tomato-bruschetta-articleLarge.jpg",
  },
  {
    id: 12,
    title: "Dim Sums",
    serviceTime: "24-30min",
    deliveryFee: 1.5,
    category: "dish",
    cuisine: "chinese",
    rating: 2,
    price: 4100,
    coverSrc: "/imagez/dishes/dimsums.jpg",
  },
];
